// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReduxCartBE.DbContext;

#nullable disable

namespace ReduxCartBE.Migrations
{
    [DbContext(typeof(ReduxCartDbContext))]
    partial class ReduxCartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReduxCartBE.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Arctic White",
                            Name = "Suhr Classic Stratocaster",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "BlueBerry Burst",
                            Name = "Gibson Les Paul",
                            Price = 3200.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sunburst",
                            Name = "Fender Telecaster",
                            Price = 800.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pea Pea",
                            Name = "Customer P90 Stratocaster",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Classic Wood",
                            Name = "Taylor 814c",
                            Price = 3000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
